# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '1.1.dev4+g4c76a90.d20230502'
__version_tuple__ = version_tuple = (1, 1, 'dev4', 'g4c76a90.d20230502')
